version = 1

[[annotations]]
path = ["adt_generate_qt.m"]
precedence = "override"
comment = "reuse can't parse this file"
SPDX-FileCopyrightText = "Copyright (C) 2021 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GPL-3.0-only WITH Qt-GPL-exception-1.0"
